# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashby', '0004_auto_20160926_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='files/'),
        ),
    ]
