# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashby', '0006_auto_20160926_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
