# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashby', '0008_auto_20160927_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extension',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
