# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashby', '0016_delete_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
