# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashby', '0019_auto_20160930_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'permissions': (('public_access', 'Everyone can see the file'),)},
        ),
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
