# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashby', '0020_auto_20161002_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
