# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashby', '0021_auto_20161002_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
