# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashby', '0023_auto_20161003_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='accesible_by',
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
