# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 00:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashby', '0024_auto_20161003_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.AddField(
            model_name='document',
            name='accesible_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
