# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashby', '0026_document_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_active',
        ),
    ]
