# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashby', '0028_auto_20161004_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadedByAsUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowedUsersAsUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
